feat: Добавить spring boot и maven  проект. Настроить эндпоинты.
AlexanderKolnakov/java-filmorate pull request #1
Opened 2022-09-14 14:48 UTC by AlexanderKolnakov

2022-09-14 19:29 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +package ru.yandex.practicum.filmorate.controllers;
Пакеты лучше наименовать в единственном числе. model в единственном, а controllers во множественном. Лучше все в единственном

2022-09-14 19:49 UTC, EvgenyKoptubenko commented on pom.xml
> +			<artifactId>logbook-spring-boot-starter</artifactId>
Для чего эта зависимость? Похоже она не используется нигде

2022-09-14 19:53 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        film.setId(filmsID);
можно написать film.setId(filmsID++);

2022-09-14 20:08 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    void tryToCreateFilmWithLongDescriptionBadRequest() throws Exception {
В тестах копи паст. Там, где копи паст почти всегда можно переделать тесты на параметризованные.
Попробуй
@ParameterizedTest
    @MethodSource("paramsForTests")
    void tryToCreateFilmWithLongNegativeDurationBadRequest(String errorMessage, int stringLength) throws Exception {
        System.out.println("errorMessage = ["+errorMessage+"] stringLength = ["+stringLength+"]");
        Film film = new Film("name", RandomString.make(stringLength), FILMS_BORN.plusDays(10), 0);
        String body = objectMapper.writeValueAsString(film);
        this.mockMvc.perform(
                        post("/films").content(body).contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isBadRequest())
                .andExpect(result -> assertTrue(result.getResolvedException() instanceof MethodArgumentNotValidException))
                .andExpect(result -> assertTrue(
                        result.getResolvedException().getMessage().contains(errorMessage)));
    }

    private static Stream<Arguments> paramsForTests() {
        return Stream.of(
                arguments("Продолжительность фильма должна быть положительным целочисленным числом.", 100),
                arguments("Описание фильма должно содержать не более 200 символов", 201)
        );
    }

2022-09-14 20:11 UTC, EvgenyKoptubenko requested changes
Замечаний практически нет. Есть предложение убрать копи паст в тестах и начать использовать параметризованные тесты, если есть желание. Если нет, то присылай - все сделано на текущий момент хорошо

2022-09-15 07:48 UTC, AlexanderKolnakov commented
Поправил замечания кроме тестов. Если честно не могу сообразить как в данном случае использовать параметризированные тесты. Допустим в схожих тестах, где ловлю BadRequest в каждом тесте меняются параметры объекта Film и строка ответа, в проверках. В шапку теста @Values() я же могу передать только параметры одного типа (например массив строк). И единственное что придумал как это использовать, создать  несколько Листов общих для всех тестов (List фильмов и List сообщений которые сравниваю) и в параметры теста передать массив чисел. А уже в тесте использовать эти числа как порядковый номер нужного объекта из данных Листов.

2022-09-15 19:44 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Попробуй все-таки в будущем сделать параметризованные тесты.

2022-09-16 07:38 UTC, merged